### PR TITLE
Unified Theme

### PR DESCRIPTION
**Pull request by SandTechStuff**
This theme unifies the calendar and notification center to be one panel instead of two floating apart. The same is applied to the control center and media actions.

screenshot-small
screenshot-small2

### CODE REVIEW

**Comment by SandTechStuff** [comment]
I put this together while messing with the mod and I liked the result, let me know if any changes need to be made.

**Comment by m417z** [comment]
Thanks, looks great! Please update the main readme file as well. Use `screenshot(2).png` to the full-size screenshots and have a small screenshot, `screenshot-small.png` (one screenshot, perhaps unified), for the main readme. See the other theme for an example.

**Comment by SandTechStuff** [comment]
I have made the changes, let me know if I missed anything.

**Comment by m417z** [comment]
Thanks. I'll make a couple of edits and will publish a new mod version.

**Pull request merged**
